package top.xfunny.mod;

import org.mtr.mapping.holder.Block;
import org.mtr.mapping.holder.Identifier;
import org.mtr.mapping.mapper.BlockHelper;
import org.mtr.mapping.registry.BlockRegistryObject;
import org.mtr.mod.block.BlockTicketMachine;
import top.xfunny.mod.block.*;

import static org.mtr.mod.Blocks.createDefaultBlockSettings;

public class Blocks {

    public static final BlockRegistryObject TEST_LIFT_BUTTONS;
    public static final BlockRegistryObject TEST_LIFT_BUTTONS_WITHOUT_SCREEN;
    public static final BlockRegistryObject TEST_LIFT_HALL_LANTERNS;
    public static final BlockRegistryObject TEST_LIFT_PANEL;
    public static final BlockRegistryObject TEST_LIFT_DESTINATION_DISPATCH_TERMINAL;

    public static final BlockRegistryObject CES_SCREEN_1_ODD = BlockFixtures.get("ces_screen_1_odd");
    public static final BlockRegistryObject CES_SCREEN_1_EVEN = BlockFixtures.get("ces_screen_1_even");

    public static final BlockRegistryObject DEWHURST_US81_BUTTON_1 = BlockFixtures.get("dewhurst_us81_button_1");
    public static final BlockRegistryObject DEWHURST_US89_BUTTON_1 = BlockFixtures.get("dewhurst_us89_button_1");
    public static final BlockRegistryObject DEWHURST_US91_BUTTON_1 = BlockFixtures.get("dewhurst_us91_button_1");
    public static final BlockRegistryObject DEWHURST_US91_BUTTON_1_BRAILLE = BlockFixtures.get("dewhurst_us91_button_1_braille");

    public static final BlockRegistryObject DOVER_IMPULSE_BUTTON_1 = BlockFixtures.get("dover_impulse_button_1");
    public static final BlockRegistryObject DOVER_IMPULSE_LANTERN_1_HORIZONTAL_ODD = BlockFixtures.get("dover_impulse_lantern_1_horizontal_odd");
    public static final BlockRegistryObject DOVER_IMPULSE_LANTERN_1_HORIZONTAL_EVEN = BlockFixtures.get("dover_impulse_lantern_1_horizontal_even");

    public static final BlockRegistryObject FUJITEC_MIC400_BUTTON_1 = BlockFixtures.get("fujitec_mic400_button_1");
    public static final BlockRegistryObject FUJITEC_MIC400_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("fujitec_mic400_button_1_without_screen");
    public static final BlockRegistryObject FUJITEC_MIC400_BUTTON_1_OLD = BlockFixtures.get("fujitec_mic400_button_1_old");
    public static final BlockRegistryObject FUJITEC_MIC400_BUTTON_1_OLD_WITHOUT_SCREEN = BlockFixtures.get("fujitec_mic400_button_1_old_without_screen");
    public static final BlockRegistryObject FUJITEC_MIC400_SCREEN_1_VERTICAL_ODD = BlockFixtures.get("fujitec_mic400_screen_1_vertical_odd");
    public static final BlockRegistryObject FUJITEC_MIC400_SCREEN_1_VERTICAL_EVEN = BlockFixtures.get("fujitec_mic400_screen_1_vertical_even");
    public static final BlockRegistryObject FUJITEC_MIC400_SCREEN_1_HORIZONTAL_ODD = BlockFixtures.get("fujitec_mic400_screen_1_horizontal_odd");
    public static final BlockRegistryObject FUJITEC_MIC400_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("fujitec_mic400_screen_1_horizontal_even");

    public static final BlockRegistryObject KONE_KDS220_BUTTON_1 = BlockFixtures.get("kone_kds220_surface_button_1");
    public static final BlockRegistryObject KONE_KDS220_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("kone_kds220_surface_button_1_without_screen");
    public static final BlockRegistryObject KONE_KDS220_SCREEN_1_ODD = BlockFixtures.get("kone_kds220_surface_screen_1_odd");
    public static final BlockRegistryObject KONE_KDS220_SCREEN_1_EVEN = BlockFixtures.get("kone_kds220_surface_screen_1_even");
    public static final BlockRegistryObject KONE_KDS330_BUTTON_1 = BlockFixtures.get("kone_kds330_surface_button_1");
    public static final BlockRegistryObject KONE_KDS330_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("kone_kds330_surface_button_1_without_screen");
    public static final BlockRegistryObject KONE_KDS330_BUTTON_1_TOUCH = BlockFixtures.get("kone_kds330_surface_button_1_touch");
    public static final BlockRegistryObject KONE_KDS330_BUTTON_1_TOUCH_WITHOUT_SCREEN = BlockFixtures.get("kone_kds330_surface_button_1_touch_without_screen");
    public static final BlockRegistryObject KONE_KDS330_LANTERN_1 = BlockFixtures.get("kone_kds330_surface_lantern_1");
    public static final BlockRegistryObject KONE_KDS330_SCREEN_1_ODD = BlockFixtures.get("kone_kds330_surface_screen_1_odd");
    public static final BlockRegistryObject KONE_KDS330_SCREEN_1_EVEN = BlockFixtures.get("kone_kds330_surface_screen_1_even");
    public static final BlockRegistryObject KONE_KDS360_BUTTON_1 = BlockFixtures.get("kone_kds360_surface_button_1");
    public static final BlockRegistryObject KONE_KDS360_BUTTON_1_DISPLAY_TOP = BlockFixtures.get("kone_kds360_surface_button_1_display_top");
    public static final BlockRegistryObject KONE_KDS360_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("kone_kds360_surface_button_1_without_screen");
    public static final BlockRegistryObject KONE_KSS280_BUTTON_1 = BlockFixtures.get("kone_kss280_surface_button_1");
    public static final BlockRegistryObject KONE_KSS280_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("kone_kss280_surface_button_1_without_screen");
    public static final BlockRegistryObject KONE_KSS280_SCREEN_1_ODD = BlockFixtures.get("kone_kss280_surface_screen_1_odd");
    public static final BlockRegistryObject KONE_KSS280_SCREEN_1_EVEN = BlockFixtures.get("kone_kss280_surface_screen_1_even");
    public static final BlockRegistryObject KONE_M_BUTTON_1 = BlockFixtures.get("kone_m_button_1");
    public static final BlockRegistryObject KONE_M_BUTTON_2 = BlockFixtures.get("kone_m_button_2");
    public static final BlockRegistryObject KONE_M_SCREEN_1_ODD = BlockFixtures.get("kone_m_screen_1_odd");
    public static final BlockRegistryObject KONE_M_SCREEN_1_EVEN = BlockFixtures.get("kone_m_screen_1_even");
    public static final BlockRegistryObject KONE_M_SCREEN_1_SMALL_ODD = BlockFixtures.get("kone_m_screen_1_small_odd");
    public static final BlockRegistryObject KONE_M_SCREEN_1_SMALL_EVEN = BlockFixtures.get("kone_m_screen_1_small_even");

    public static final BlockRegistryObject OTIS_GEN3_BUTTON_1 = BlockFixtures.get("otis_gen3_button_1");
    public static final BlockRegistryObject OTIS_SERIES_1_BUTTON_1 = BlockFixtures.get("otis_series_1_button_1");
    public static final BlockRegistryObject OTIS_SERIES_1_BUTTON_2 = BlockFixtures.get("otis_series_1_button_2");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_1 = BlockFixtures.get("otis_series_1_screen_1");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_1_EVEN = BlockFixtures.get("otis_series_1_screen_1_even");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_1_HORIZONTAL = BlockFixtures.get("otis_series_1_screen_1_horizontal");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_screen_1_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_1_EVEN = BlockFixtures.get("otis_series_1_lantern_1_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_1_ODD = BlockFixtures.get("otis_series_1_lantern_1_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_1_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_lantern_1_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_1_HORIZONTAL_ODD = BlockFixtures.get("otis_series_1_lantern_1_horizontal_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_1_EVEN = BlockFixtures.get("otis_series_1_lantern_screen_1_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_1_ODD = BlockFixtures.get("otis_series_1_lantern_screen_1_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_lantern_screen_1_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_1_HORIZONTAL_ODD = BlockFixtures.get("otis_series_1_lantern_screen_1_horizontal_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_2 = BlockFixtures.get("otis_series_1_screen_2");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_2_EVEN = BlockFixtures.get("otis_series_1_screen_2_even");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_2_HORIZONTAL = BlockFixtures.get("otis_series_1_screen_2_horizontal");
    public static final BlockRegistryObject OTIS_SERIES_1_SCREEN_2_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_screen_2_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_2_EVEN = BlockFixtures.get("otis_series_1_lantern_2_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_2_ODD = BlockFixtures.get("otis_series_1_lantern_2_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_2_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_lantern_2_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_2_HORIZONTAL_ODD = BlockFixtures.get("otis_series_1_lantern_2_horizontal_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_2_EVEN = BlockFixtures.get("otis_series_1_lantern_screen_2_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_2_ODD = BlockFixtures.get("otis_series_1_lantern_screen_2_odd");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_2_HORIZONTAL_EVEN = BlockFixtures.get("otis_series_1_lantern_screen_2_horizontal_even");
    public static final BlockRegistryObject OTIS_SERIES_1_LANTERN_SCREEN_2_HORIZONTAL_ODD = BlockFixtures.get("otis_series_1_lantern_screen_2_horizontal_odd");
    public static final BlockRegistryObject OTIS_SERIES_3_BUTTON_1 = BlockFixtures.get("otis_series_3_button_1");
    public static final BlockRegistryObject OTIS_SERIES_3_SCREEN_1_ODD = BlockFixtures.get("otis_series_3_screen_1_odd");
    public static final BlockRegistryObject OTIS_SERIES_3_SCREEN_1_EVEN = BlockFixtures.get("otis_series_3_screen_1_even");
    public static final BlockRegistryObject OTIS_SERIES_3_ELD_SCREEN_1_ODD = BlockFixtures.get("otis_series_3_eld_screen_1_odd");
    public static final BlockRegistryObject OTIS_SERIES_3_ELD_SCREEN_1_EVEN = BlockFixtures.get("otis_series_3_eld_screen_1_even");
    public static final BlockRegistryObject OTIS_SERIES_3_LANTERN_1_ARROW_ODD = BlockFixtures.get("otis_series_3_lantern_1_arrow_odd");
    public static final BlockRegistryObject OTIS_SERIES_3_LANTERN_1_ARROW_EVEN = BlockFixtures.get("otis_series_3_lantern_1_arrow_even");
    public static final BlockRegistryObject OTIS_SPEC_60_BUTTON_1 = BlockFixtures.get("otis_spec_60_button_1");
    public static final BlockRegistryObject OTIS_SPEC_90_BUTTON_1_BLACK = BlockFixtures.get("otis_spec_90_button_1_black");
    public static final BlockRegistryObject OTIS_SPEC_90_BUTTON_1_WHITE = BlockFixtures.get("otis_spec_90_button_1_white");
    public static final BlockRegistryObject OTIS_SPEC_90_BUTTON_2_BLACK = BlockFixtures.get("otis_spec_90_button_2_black");
    public static final BlockRegistryObject OTIS_SPEC_90_BUTTON_2_WHITE = BlockFixtures.get("otis_spec_90_button_2_white");

    public static final BlockRegistryObject MITSUBISHI_GPS_BUTTON_1 = BlockFixtures.get("mitsubishi_gps_button_1");
    public static final BlockRegistryObject MITSUBISHI_GPS_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_gps_button_1_without_screen");
    public static final BlockRegistryObject MITSUBISHI_BUTTON_SHUN_HING_SQUARE = BlockFixtures.get("mitsubishi_button_shun_hing_square");
    public static final BlockRegistryObject MITSUBISHI_RYODEN_SCREEN_1_EVEN = BlockFixtures.get("mitsubishi_ryoden_screen_1_even");
    public static final BlockRegistryObject MITSUBISHI_RYODEN_SCREEN_1_ODD = BlockFixtures.get("mitsubishi_ryoden_screen_1_odd");
    public static final BlockRegistryObject MITSUBISHI_RYODEN_SCREEN_2_EVEN = BlockFixtures.get("mitsubishi_ryoden_screen_2_even");
    public static final BlockRegistryObject MITSUBISHI_RYODEN_SCREEN_2_ODD = BlockFixtures.get("mitsubishi_ryoden_screen_2_odd");
    public static final BlockRegistryObject MITSUBISHI_GPS3_BUTTON_1 = BlockFixtures.get("mitsubishi_gps3_button_1");
    public static final BlockRegistryObject MITSUBISHI_GPS3_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_gps3_button_1_without_screen");
    public static final BlockRegistryObject MITSUBISHI_GPS3_BUTTON_2 = BlockFixtures.get("mitsubishi_gps3_button_2");
    public static final BlockRegistryObject MITSUBISHI_GPS3_BUTTON_2_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_gps3_button_2_without_screen");
    public static final BlockRegistryObject MITSUBISHI_GPS3_SCREEN_1_EVEN = BlockFixtures.get("mitsubishi_gps3_screen_1_even");
    public static final BlockRegistryObject MITSUBISHI_GPS3_SCREEN_1_ODD = BlockFixtures.get("mitsubishi_gps3_screen_1_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_1 = BlockFixtures.get("mitsubishi_nexway_button_1");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_1_SEGMENTED = BlockFixtures.get("mitsubishi_nexway_button_1_segmented");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_nexway_button_1_without_screen");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_2 = BlockFixtures.get("mitsubishi_nexway_button_2");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_2_SEGMENTED = BlockFixtures.get("mitsubishi_nexway_button_2_segmented");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_2_LCD_1 = BlockFixtures.get("mitsubishi_nexway_button_2_lcd_1");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_2_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_nexway_button_2_without_screen");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_3 = BlockFixtures.get("mitsubishi_nexway_button_3");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_3_SEGMENTED = BlockFixtures.get("mitsubishi_nexway_button_3_segmented");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_3_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_nexway_button_3_without_screen");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_4 = BlockFixtures.get("mitsubishi_nexway_button_4");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_4_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_nexway_button_4_without_screen");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_5 = BlockFixtures.get("mitsubishi_nexway_button_5");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_BUTTON_5_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_nexway_button_5_without_screen");
    public static final BlockRegistryObject MITSUBISHI_BUTTON_SHT = BlockFixtures.get("mitsubishi_button_sht");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_1_GOLD = BlockFixtures.get("mitsubishi_maxiez_button_1_gold");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_1_SILVER = BlockFixtures.get("mitsubishi_maxiez_button_1_silver");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_2 = BlockFixtures.get("mitsubishi_maxiez_button_2");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_2_LCD = BlockFixtures.get("mitsubishi_maxiez_button_2_lcd");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_2_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_maxiez_button_2_without_screen");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_3 = BlockFixtures.get("mitsubishi_maxiez_button_3");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_3_LCD = BlockFixtures.get("mitsubishi_maxiez_button_3_lcd");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_BUTTON_3_WITHOUT_SCREEN = BlockFixtures.get("mitsubishi_maxiez_button_3_without_screen");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_SCREEN_1_EVEN = BlockFixtures.get("mitsubishi_maxiez_screen_1_even");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_SCREEN_1_ODD = BlockFixtures.get("mitsubishi_maxiez_screen_1_odd");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_SCREEN_2_EVEN = BlockFixtures.get("mitsubishi_maxiez_screen_2_even");
    public static final BlockRegistryObject MITSUBISHI_MAXIEZ_SCREEN_2_ODD = BlockFixtures.get("mitsubishi_maxiez_screen_2_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_ODD = BlockFixtures.get("mitsubishi_nexway_lantern_1_horizontal_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_EVEN = BlockFixtures.get("mitsubishi_nexway_lantern_1_horizontal_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_ODD = BlockFixtures.get("mitsubishi_nexway_lantern_1_vertical_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_EVEN = BlockFixtures.get("mitsubishi_nexway_lantern_1_vertical_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_2_HORIZONTAL_ODD = BlockFixtures.get("mitsubishi_nexway_lantern_2_horizontal_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_2_HORIZONTAL_EVEN = BlockFixtures.get("mitsubishi_nexway_lantern_2_horizontal_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_2_VERTICAL_ODD = BlockFixtures.get("mitsubishi_nexway_lantern_2_vertical_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_2_VERTICAL_EVEN = BlockFixtures.get("mitsubishi_nexway_lantern_2_vertical_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_3_ODD = BlockFixtures.get("mitsubishi_nexway_lantern_3_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_LANTERN_3_EVEN = BlockFixtures.get("mitsubishi_nexway_lantern_3_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_1_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_1_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_1_ODD = BlockFixtures.get("mitsubishi_nexway_screen_1_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_1_segmented_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_ODD = BlockFixtures.get("mitsubishi_nexway_screen_1_segmented_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_2_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_2_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_2_ODD = BlockFixtures.get("mitsubishi_nexway_screen_2_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_3_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_ODD = BlockFixtures.get("mitsubishi_nexway_screen_3_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_3_segmented_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_ODD = BlockFixtures.get("mitsubishi_nexway_screen_3_segmented_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_WIDE_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_3_wide_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_WIDE_ODD = BlockFixtures.get("mitsubishi_nexway_screen_3_wide_odd");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_WIDE_SEGMENTED_EVEN = BlockFixtures.get("mitsubishi_nexway_screen_3_wide_segmented_even");
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_SCREEN_3_WIDE_SEGMENTED_ODD = BlockFixtures.get("mitsubishi_nexway_screen_3_wide_segmented_odd");
    public static final BlockRegistryObject MITSUBISHI_MPVF_BUTTON_1 = BlockFixtures.get("mitsubishi_mpvf_button_1");
    public static final BlockRegistryObject MITSUBISHI_MPVF_SCREEN_1_HORIZONTAL_ODD = BlockFixtures.get("mitsubishi_mpvf_screen_1_horizontal_odd");
    public static final BlockRegistryObject MITSUBISHI_MPVF_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("mitsubishi_mpvf_screen_1_horizontal_even");
    public static final BlockRegistryObject MITSUBISHI_MPVF_SCREEN_1_VERTICAL_ODD = BlockFixtures.get("mitsubishi_mpvf_screen_1_vertical_odd");
    public static final BlockRegistryObject MITSUBISHI_MPVF_SCREEN_1_VERTICAL_EVEN = BlockFixtures.get("mitsubishi_mpvf_screen_1_vertical_even");
    public static final BlockRegistryObject MITSUBISHI_MPVF_LANTERN_1_HORIZONTAL_ODD = BlockFixtures.get("mitsubishi_mpvf_lantern_1_horizontal_odd");
    public static final BlockRegistryObject MITSUBISHI_MPVF_LANTERN_1_HORIZONTAL_EVEN = BlockFixtures.get("mitsubishi_mpvf_lantern_1_horizontal_even");
    public static final BlockRegistryObject MITSUBISHI_MPVF_LANTERN_1_VERTICAL_ODD = BlockFixtures.get("mitsubishi_mpvf_lantern_1_vertical_odd");
    public static final BlockRegistryObject MITSUBISHI_MPVF_LANTERN_1_VERTICAL_EVEN = BlockFixtures.get("mitsubishi_mpvf_lantern_1_vertical_even");
    public static final BlockRegistryObject MITSUBISHI_MP_BUTTON_1 = BlockFixtures.get("mitsubishi_mp_button_1");
    public static final BlockRegistryObject MITSUBISHI_MP_BUTTON_1_TOUCH = BlockFixtures.get("mitsubishi_mp_button_1_touch");

    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_NEXWAY_CR_BUTTON_1 = BlockFixtures.get("shanghai_mitsubishi_nexway_cr_button_1");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1 = BlockFixtures.get("shanghai_mitsubishi_lehy_3_button_1");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("shanghai_mitsubishi_lehy_3_button_1_without_screen");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_2 = BlockFixtures.get("shanghai_mitsubishi_lehy_3_button_2");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_3_LCD = BlockFixtures.get("shanghai_mitsubishi_lehy_3_button_3_lcd");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_EVEN = BlockFixtures.get("shanghai_mitsubishi_lehy_3_screen_1_even");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_ODD = BlockFixtures.get("shanghai_mitsubishi_lehy_3_screen_1_odd");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_EVEN = BlockFixtures.get("shanghai_mitsubishi_lehy_3_screen_1_wide_even");
    public static final BlockRegistryObject SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_ODD = BlockFixtures.get("shanghai_mitsubishi_lehy_3_screen_1_wide_odd");

    public static final BlockRegistryObject SCHINDLER_D_SERIES_D2BUTTON = BlockFixtures.get("schindler_d_series_d2button");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_1_ODD = BlockFixtures.get("schindler_d_series_screen_1_odd");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_1_EVEN = BlockFixtures.get("schindler_d_series_screen_1_even");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_GREEN_EVEN = BlockFixtures.get("schindler_d_series_screen_2_green_even");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_BLUE_EVEN = BlockFixtures.get("schindler_d_series_screen_2_blue_even");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_RED_EVEN = BlockFixtures.get("schindler_d_series_screen_2_red_even");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_GREEN_ODD = BlockFixtures.get("schindler_d_series_screen_2_green_odd");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_BLUE_ODD = BlockFixtures.get("schindler_d_series_screen_2_blue_odd");
    public static final BlockRegistryObject SCHINDLER_D_SERIES_SCREEN_2_RED_ODD = BlockFixtures.get("schindler_d_series_screen_2_red_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_BUTTON = BlockFixtures.get("schindler_m_series_button");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_TOUCH_BUTTON = BlockFixtures.get("schindler_m_series_touch_button");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_ROUND_TOUCH_BUTTON = BlockFixtures.get("schindler_m_series_round_touch_button");
    public static final BlockRegistryObject SCHINDLER_S_SERIES_GREY_BUTTON = BlockFixtures.get("schindler_s_series_grey_button");
    public static final BlockRegistryObject SCHINDLER_S_SERIES_DARK_GREY_BUTTON = BlockFixtures.get("schindler_s_series_dark_grey_button");
    public static final BlockRegistryObject SCHINDLER_S_SERIES_BLUE_BUTTON = BlockFixtures.get("schindler_s_series_blue_button");
    public static final BlockRegistryObject SCHINDLER_R_SERIES_ROUND_BUTTON = BlockFixtures.get("schindler_r_series_round_button");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_ROUND_LANTERN_1_ODD = BlockFixtures.get("schindler_m_series_round_lantern_1_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_ROUND_LANTERN_1_EVEN = BlockFixtures.get("schindler_m_series_round_lantern_1_even");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_1 = BlockFixtures.get("schindler_m_series_screen_1");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_1_EVEN = BlockFixtures.get("schindler_m_series_screen_1_even");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_2_ODD = BlockFixtures.get("schindler_m_series_screen_2_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_2_EVEN = BlockFixtures.get("schindler_m_series_screen_2_even");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_3_ODD = BlockFixtures.get("schindler_m_series_screen_3_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_3_EVEN = BlockFixtures.get("schindler_m_series_screen_3_even");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_4_ODD = BlockFixtures.get("schindler_m_series_screen_4_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_4_EVEN = BlockFixtures.get("schindler_m_series_screen_4_even");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_5_ODD = BlockFixtures.get("schindler_m_series_screen_5_odd");
    public static final BlockRegistryObject SCHINDLER_M_SERIES_SCREEN_5_EVEN = BlockFixtures.get("schindler_m_series_screen_5_even");
    public static final BlockRegistryObject SCHINDLER_R_SERIES_SCREEN_1_ODD = BlockFixtures.get("schindler_r_series_screen_1_odd");
    public static final BlockRegistryObject SCHINDLER_R_SERIES_SCREEN_1_EVEN = BlockFixtures.get("schindler_r_series_screen_1_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_1_WHITE = BlockFixtures.get("schindler_linea_button_1_white");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_1_WHITE_WITHOUT_SCREEN = BlockFixtures.get("schindler_linea_button_1_white_without_screen");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_1_BLACK = BlockFixtures.get("schindler_linea_button_1_black");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_1_BLACK_WITHOUT_SCREEN = BlockFixtures.get("schindler_linea_button_1_black_without_screen");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_2_WHITE = BlockFixtures.get("schindler_linea_button_2_white");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_2_WHITE_WITHOUT_SCREEN = BlockFixtures.get("schindler_linea_button_2_white_without_screen");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_2_BLACK = BlockFixtures.get("schindler_linea_button_2_black");
    public static final BlockRegistryObject SCHINDLER_LINEA_BUTTON_2_BLACK_WITHOUT_SCREEN = BlockFixtures.get("schindler_linea_button_2_black_without_screen");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_ODD = BlockFixtures.get("schindler_linea_screen_1_white_horizontal_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_EVEN = BlockFixtures.get("schindler_linea_screen_1_white_horizontal_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_ODD = BlockFixtures.get("schindler_linea_screen_1_white_vertical_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_EVEN = BlockFixtures.get("schindler_linea_screen_1_white_vertical_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_ODD = BlockFixtures.get("schindler_linea_screen_1_black_horizontal_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_EVEN = BlockFixtures.get("schindler_linea_screen_1_black_horizontal_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_ODD = BlockFixtures.get("schindler_linea_screen_1_black_vertical_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_EVEN = BlockFixtures.get("schindler_linea_screen_1_black_vertical_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_ODD = BlockFixtures.get("schindler_linea_screen_2_white_horizontal_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_EVEN = BlockFixtures.get("schindler_linea_screen_2_white_horizontal_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_ODD = BlockFixtures.get("schindler_linea_screen_2_white_vertical_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_EVEN = BlockFixtures.get("schindler_linea_screen_2_white_vertical_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_ODD = BlockFixtures.get("schindler_linea_screen_2_black_horizontal_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_EVEN = BlockFixtures.get("schindler_linea_screen_2_black_horizontal_even");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_ODD = BlockFixtures.get("schindler_linea_screen_2_black_vertical_odd");
    public static final BlockRegistryObject SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_EVEN = BlockFixtures.get("schindler_linea_screen_2_black_vertical_even");
    public static final BlockRegistryObject SCHINDLER_FI_GS_BUTTON_1 = BlockFixtures.get("schindler_fi_gs_button_1");
    public static final BlockRegistryObject SCHINDLER_FI_GS_TOUCH_BUTTON_1 = BlockFixtures.get("schindler_fi_gs_touch_button_1");
    public static final BlockRegistryObject SCHINDLER_FI_GS_TOUCH_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("schindler_fi_gs_touch_button_1_without_screen");
    public static final BlockRegistryObject SCHINDLER_FI_GS_BUTTON_1_STEEL = BlockFixtures.get("schindler_fi_gs_button_1_steel");
    public static final BlockRegistryObject SCHINDLER_FI_GS_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("schindler_fi_gs_button_1_without_screen");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_STEEL_ODD = BlockFixtures.get("schindler_fi_gs_screen_1_steel_odd");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_STEEL_EVEN = BlockFixtures.get("schindler_fi_gs_screen_1_steel_even");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_BLACK_ODD = BlockFixtures.get("schindler_fi_gs_screen_1_black_odd");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_BLACK_EVEN = BlockFixtures.get("schindler_fi_gs_screen_1_black_even");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_GREY_ODD = BlockFixtures.get("schindler_fi_gs_screen_1_grey_odd");
    public static final BlockRegistryObject SCHINDLER_FI_GS_SCREEN_1_GREY_EVEN = BlockFixtures.get("schindler_fi_gs_screen_1_grey_even");
    public static final BlockRegistryObject SCHINDLER_Z_LINE_3_KEYPAD_1 = BlockFixtures.get("schindler_z_line_3_keypad_1");

    public static final BlockRegistryObject TKE_MS5E_BUTTON_1 = BlockFixtures.get("tke_ms5e_button_1");
    public static final BlockRegistryObject THYSSENKRUPP_MS5E_BUTTON_1 = BlockFixtures.get("thyssenkrupp_ms5e_button_1");
    public static final BlockRegistryObject THYSSENKRUPP_MS3E_BUTTON_1 = BlockFixtures.get("thyssenkrupp_ms3e_button_1");
    public static final BlockRegistryObject THYSSENKRUPP_AL_C01_BUTTON_1 = BlockFixtures.get("thyssenkrupp_al_c01_button_1");
    public static final BlockRegistryObject THYSSENKRUPP_S001_BUTTON_1 = BlockFixtures.get("thyssenkrupp_s001_button_1");
    public static final BlockRegistryObject THYSSENKRUPP_S001_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("thyssenkrupp_s001_button_1_without_screen");
    public static final BlockRegistryObject THYSSENKRUPP_SF000_SCREEN_1_ODD = BlockFixtures.get("thyssenkrupp_sf000_screen_1_odd");
    public static final BlockRegistryObject THYSSENKRUPP_SF000_SCREEN_1_EVEN = BlockFixtures.get("thyssenkrupp_sf000_screen_1_even");

    public static final BlockRegistryObject HITACHI_B85_BUTTON_1 = BlockFixtures.get("hitachi_b85_button_1");
    public static final BlockRegistryObject HITACHI_B85_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("hitachi_b85_button_1_without_screen");
    public static final BlockRegistryObject HITACHI_B85_BUTTON_2 = BlockFixtures.get("hitachi_b85_button_2");
    public static final BlockRegistryObject HITACHI_B85_SCREEN_1_VERTICAL_ODD = BlockFixtures.get("hitachi_b85_screen_1_vertical_odd");
    public static final BlockRegistryObject HITACHI_B85_SCREEN_1_VERTICAL_EVEN = BlockFixtures.get("hitachi_b85_screen_1_vertical_even");
    public static final BlockRegistryObject HITACHI_B85_SCREEN_1_HORIZONTAL_ODD = BlockFixtures.get("hitachi_b85_screen_1_horizontal_odd");
    public static final BlockRegistryObject HITACHI_B85_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("hitachi_b85_screen_1_horizontal_even");
    public static final BlockRegistryObject HITACHI_B89_BUTTON_1 = BlockFixtures.get("hitachi_b89_button_1");
    public static final BlockRegistryObject HITACHI_B89_BUTTON_1_WITHOUT_SCREEN = BlockFixtures.get("hitachi_b89_button_1_without_screen");
    public static final BlockRegistryObject HITACHI_B89_BUTTON_2 = BlockFixtures.get("hitachi_b89_button_2");
    public static final BlockRegistryObject HITACHI_B89_SCREEN_1_VERTICAL_ODD = BlockFixtures.get("hitachi_b89_screen_1_vertical_odd");
    public static final BlockRegistryObject HITACHI_B89_SCREEN_1_VERTICAL_EVEN = BlockFixtures.get("hitachi_b89_screen_1_vertical_even");
    public static final BlockRegistryObject HITACHI_B89_SCREEN_1_HORIZONTAL_ODD = BlockFixtures.get("hitachi_b89_screen_1_horizontal_odd");
    public static final BlockRegistryObject HITACHI_B89_SCREEN_1_HORIZONTAL_EVEN = BlockFixtures.get("hitachi_b89_screen_1_horizontal_even");

    public static final BlockRegistryObject HITACHI_BUTTON_PAFC = BlockFixtures.get("hitachi_button_pafc");

    public static final BlockRegistryObject HITACHI_VIB320_BUTTON = BlockFixtures.get("hitachi_vib320_button_1");
    public static final BlockRegistryObject HITACHI_VIB320_BUTTON_DOT_MATRIX = BlockFixtures.get("hitachi_vib320_button_1_dot_matrix");
    public static final BlockRegistryObject HITACHI_VIB320_BUTTON_HIP43 = BlockFixtures.get("hitachi_vib320_button_1_hip43");
    public static final BlockRegistryObject HITACHI_VIB322_BUTTON = BlockFixtures.get("hitachi_vib322_button_1");
    public static final BlockRegistryObject HITACHI_VIB322_BUTTON_DOT_MATRIX = BlockFixtures.get("hitachi_vib322_button_1_dot_matrix");
    public static final BlockRegistryObject HITACHI_VIB325_BUTTON = BlockFixtures.get("hitachi_vib325_button_1");
    public static final BlockRegistryObject HITACHI_VIB325_BUTTON_DOT_MATRIX = BlockFixtures.get("hitachi_vib325_button_1_dot_matrix");
    public static final BlockRegistryObject HITACHI_VIB221_BUTTON = BlockFixtures.get("hitachi_vib221_button_1");
    public static final BlockRegistryObject HITACHI_VIB221_BUTTON_DOT_MATRIX = BlockFixtures.get("hitachi_vib221_button_1_dot_matrix");
    public static final BlockRegistryObject HITACHI_VIB221_BUTTON_LCD_SEGMENTED = BlockFixtures.get("hitachi_vib221_button_1_lcd_segmented");
    public static final BlockRegistryObject HITACHI_VIB221_BUTTON_HIP43 = BlockFixtures.get("hitachi_vib221_button_1_hip43");
    public static final BlockRegistryObject HITACHI_VIB820_BUTTON = BlockFixtures.get("hitachi_vib820_button_1");
    public static final BlockRegistryObject HITACHI_VIB820_BUTTON_LCD = BlockFixtures.get("hitachi_vib820_button_1_lcd");
    public static final BlockRegistryObject HITACHI_VIB68_BUTTON = BlockFixtures.get("hitachi_vib68_button_1");
    public static final BlockRegistryObject HITACHI_VIB191_BUTTON = BlockFixtures.get("hitachi_vib191_button_1");
    public static final BlockRegistryObject HITACHI_VIB192_BUTTON = BlockFixtures.get("hitachi_vib192_button_1");
    public static final BlockRegistryObject HITACHI_HB820_BUTTON = BlockFixtures.get("hitachi_hb820_button_1");
    public static final BlockRegistryObject HITACHI_HSB820_BUTTON = BlockFixtures.get("hitachi_hsb820_button_1");
    public static final BlockRegistryObject HITACHI_VIB820PRO_BUTTON = BlockFixtures.get("hitachi_vib820pro_button_1");
    public static final BlockRegistryObject HITACHI_HSB820PRO_BUTTON = BlockFixtures.get("hitachi_hsb820pro_button_1");
    public static final BlockRegistryObject HITACHI_GHD820PRO_SCREEN_ODD = BlockFixtures.get("hitachi_ghd820pro_screen_1_odd");
    public static final BlockRegistryObject HITACHI_GHD820PRO_SCREEN_EVEN = BlockFixtures.get("hitachi_ghd820pro_screen_1_even");
    public static final BlockRegistryObject HITACHI_GHI675_SCREEN_ODD = BlockFixtures.get("hitachi_ghi675_screen_1_odd");
    public static final BlockRegistryObject HITACHI_GHI675_SCREEN_EVEN = BlockFixtures.get("hitachi_ghi675_screen_1_even");
    public static final BlockRegistryObject HITACHI_GHL668_LANTERN_ODD = BlockFixtures.get("hitachi_ghl668_lantern_1_odd");
    public static final BlockRegistryObject HITACHI_GHL668_LANTERN_EVEN = BlockFixtures.get("hitachi_ghl668_lantern_1_even");
    public static final BlockRegistryObject HITACHI_GHL820_LANTERN_ODD = BlockFixtures.get("hitachi_ghl820_lantern_1_odd");
    public static final BlockRegistryObject HITACHI_GHL820_LANTERN_EVEN = BlockFixtures.get("hitachi_ghl820_lantern_1_even");
    public static final BlockRegistryObject HITACHI_GHL673_LANTERN_ODD = BlockFixtures.get("hitachi_ghl673_lantern_1_odd");
    public static final BlockRegistryObject HITACHI_GHL673_LANTERN_EVEN = BlockFixtures.get("hitachi_ghl673_lantern_1_even");
    public static final BlockRegistryObject HITACHI_VIB628_BUTTON = BlockFixtures.get("hitachi_vib628_button_1");
    public static final BlockRegistryObject HITACHI_HB628_BUTTON = BlockFixtures.get("hitachi_hb628_button_1");
    public static final BlockRegistryObject HITACHI_VIB668_BUTTON = BlockFixtures.get("hitachi_vib668_button_1");
    public static final BlockRegistryObject HITACHI_VIB658_BUTTON = BlockFixtures.get("hitachi_vib658_button_1");
    public static final BlockRegistryObject HITACHI_HB658_BUTTON = BlockFixtures.get("hitachi_hb658_button_1");
    public static final BlockRegistryObject HITACHI_VIB663_BUTTON = BlockFixtures.get("hitachi_vib663_button_1");
    public static final BlockRegistryObject HITACHI_VIB681_BUTTON = BlockFixtures.get("hitachi_vib681_button_1");
    public static final BlockRegistryObject HITACHI_VIB676_BUTTON = BlockFixtures.get("hitachi_vib676_button_1");
    public static final BlockRegistryObject HITACHI_VIB679_BUTTON = BlockFixtures.get("hitachi_vib679_button_1");
    public static final BlockRegistryObject HITACHI_VIB673_BUTTON = BlockFixtures.get("hitachi_vib673_button_1");
    public static final BlockRegistryObject HITACHI_VIB673_BUTTON_HIP43 = BlockFixtures.get("hitachi_vib673_button_1_hip43");
    public static final BlockRegistryObject HITACHI_HB673_BUTTON = BlockFixtures.get("hitachi_hb673_button_1");
    public static final BlockRegistryObject HITACHI_VIB181A_BUTTON = BlockFixtures.get("hitachi_vib181a_button_1");
    public static final BlockRegistryObject HITACHI_VIB182A_BUTTON = BlockFixtures.get("hitachi_vib182a_button_1");
    public static final BlockRegistryObject HITACHI_HB181A_BUTTON = BlockFixtures.get("hitachi_hb181a_button_1");

    public static final BlockRegistryObject TONIC_DS_SCREEN_1_ODD = BlockFixtures.get("tonic_ds_screen_1_odd");
    public static final BlockRegistryObject TONIC_DS_SCREEN_1_EVEN = BlockFixtures.get("tonic_ds_screen_1_even");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_RED_ODD = BlockFixtures.get("tonic_dm_screen_1_red_odd");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_RED_EVEN = BlockFixtures.get("tonic_dm_screen_1_red_even");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_GREEN_ODD = BlockFixtures.get("tonic_dm_screen_1_green_odd");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_GREEN_EVEN = BlockFixtures.get("tonic_dm_screen_1_green_even");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_YELLOW_ODD = BlockFixtures.get("tonic_dm_screen_1_yellow_odd");
    public static final BlockRegistryObject TONIC_DM_SCREEN_1_YELLOW_EVEN = BlockFixtures.get("tonic_dm_screen_1_yellow_even");
    public static final BlockRegistryObject TOSHIBA_BUTTON_1 = BlockFixtures.get("toshiba_button_1");
    public static final BlockRegistryObject TOSHIBA_LANTERN_1_ODD = BlockFixtures.get("toshiba_lantern_1_odd");
    public static final BlockRegistryObject TOSHIBA_LANTERN_1_EVEN = BlockFixtures.get("toshiba_lantern_1_even");
    public static final BlockRegistryObject TOSHIBA_SCREEN_1_ODD = BlockFixtures.get("toshiba_screen_1_odd");
    public static final BlockRegistryObject TOSHIBA_SCREEN_1_EVEN = BlockFixtures.get("toshiba_screen_1_even");
    public static final BlockRegistryObject TOSHIBA_SCREEN_2_ODD = BlockFixtures.get("toshiba_screen_2_odd");
    public static final BlockRegistryObject TOSHIBA_SCREEN_2_EVEN = BlockFixtures.get("toshiba_screen_2_even");

    public static final BlockRegistryObject PAT_P01_TICKET_BARRIER_ENTRANCE;
    public static final BlockRegistryObject PAT_P01_TICKET_BARRIER_EXIT;
    public static final BlockRegistryObject PAT_P01_TICKET_BARRIER_BARE;
    public static final BlockRegistryObject PAT_TM01_TICKET_MACHINE;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_2_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_2_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_3_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_3_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_4_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_4_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_5_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_5_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_6_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_6_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_7_EVEN;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_7_ODD;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_MIDDLE;
    public static final BlockRegistryObject PAT_RS01_RAILWAY_SIGN_POLE;

    public static final BlockRegistryObject LIFT_TRACK_MAGNETIC_VANE;

    public static final BlockRegistryObject HITACHI_B85_DOOR_1;
    public static final BlockRegistryObject KONE_M_DOOR_1;
    public static final BlockRegistryObject MITSUBISHI_NEXWAY_DOOR_1;
    public static final BlockRegistryObject OTIS_E411_US_DOOR_1;
    public static final BlockRegistryObject SCHINDLER_QKS9_DOOR_1;

    static {

        TEST_LIFT_BUTTONS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "test_lift_buttons"), () -> new Block(new TestLiftButtons()));

        TEST_LIFT_HALL_LANTERNS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "test_lift_hall_lanterns"), () -> new Block(new TestLiftHallLanterns()));
        TEST_LIFT_PANEL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "test_lift_panel"), () -> new Block(new TestLiftPanel()));
        TEST_LIFT_BUTTONS_WITHOUT_SCREEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "test_lift_buttons_without_screen"), () -> new Block(new TestLiftButtonsWithoutScreen()));
        TEST_LIFT_DESTINATION_DISPATCH_TERMINAL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "test_lift_destination_dispatch_terminal"), () -> new Block(new TestLiftDestinationDispatchTerminal()));

        PAT_P01_TICKET_BARRIER_ENTRANCE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_p01_ticket_barrier_entrance"), () -> new Block(new PATTicketBarrier(true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_P01_TICKET_BARRIER_EXIT = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_p01_ticket_barrier_exit"), () -> new Block(new PATTicketBarrier(false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_P01_TICKET_BARRIER_BARE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_p01_ticket_barrier_bare"), () -> new Block(new PATTicketBarrierBareBlock(BlockHelper.createBlockSettings(false, true).strength(4.0f).nonOpaque())), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_TM01_TICKET_MACHINE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_tm01_ticket_machine"), () -> new Block(new BlockTicketMachine(BlockHelper.createBlockSettings(true, true, falseblockState -> 5))), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_2_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_2_even"), () -> new Block(new PATRS01RailwaySign(2, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_2_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_2_odd"), () -> new Block(new PATRS01RailwaySign(2, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_3_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_3_even"), () -> new Block(new PATRS01RailwaySign(3, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_3_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_3_odd"), () -> new Block(new PATRS01RailwaySign(3, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_4_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_4_even"), () -> new Block(new PATRS01RailwaySign(4, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_4_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_4_odd"), () -> new Block(new PATRS01RailwaySign(4, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_5_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_5_even"), () -> new Block(new PATRS01RailwaySign(5, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_5_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_5_odd"), () -> new Block(new PATRS01RailwaySign(5, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_6_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_6_even"), () -> new Block(new PATRS01RailwaySign(6, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_6_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_6_odd"), () -> new Block(new PATRS01RailwaySign(6, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_7_EVEN = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_7_even"), () -> new Block(new PATRS01RailwaySign(7, false)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_7_ODD = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_7_odd"), () -> new Block(new PATRS01RailwaySign(7, true)), CreativeModeTabs.YTE_RAILWAY_FACILITIES);
        PAT_RS01_RAILWAY_SIGN_MIDDLE = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_middle"), () -> new Block(new PATRS01RailwaySign(0, false)));
        PAT_RS01_RAILWAY_SIGN_POLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_pole"), () -> new Block(new PATRS01RailwaySignPole(createDefaultBlockSettings(false))), CreativeModeTabs.YTE_RAILWAY_FACILITIES);

        LIFT_TRACK_MAGNETIC_VANE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "lift_track_magnetic_vane"), () -> new Block(new LiftTrackMagneticVane()), CreativeModeTabs.YTE_LIFT_FIXTURES);

        HITACHI_B85_DOOR_1 = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "hitachi_b85_door_1"), () -> new Block(new HitachiB85Door1()));
        KONE_M_DOOR_1 = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "kone_m_door_1"), () -> new Block(new KoneMDoor1()));
        MITSUBISHI_NEXWAY_DOOR_1 = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "mitsubishi_nexway_door_1"), () -> new Block(new MitsubishiNexWayDoor1()));
        OTIS_E411_US_DOOR_1 = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "otis_e411_us_door_1"), () -> new Block(new OtisE411USDoor1()));
        SCHINDLER_QKS9_DOOR_1 = Init.REGISTRY.registerBlock(new Identifier(Init.MOD_ID, "schindler_qks9_door_1"), () -> new Block(new SchindlerQKS9Door1()));
    }

    public static void init() {
    }
}
