# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
minecraftVersion=1.20.1
mtrVersion=4.0.0
version=1.0.2-prerelease.3

# -------- Deploy for Testing --------
deploy.enableDownload=false
deploy.targetMtrVersion=4.0.4
deploy.maxThreads=16
deploy.mcVersions=1.16.5,1.17.1,1.18.2,1.19.2,1.19.4,1.20.1,1.20.4
deploy.loaders=fabric,forge
# Override default Minecraft dir (default: ~/.minecraft)
# deploy.minecraftDir=D:/Minecraft/test/.minecraft
